# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/linuxbrew/.linuxbrew/Cellar/cmake/3.16.2/bin/cmake

# The command to remove a file.
RM = /home/linuxbrew/.linuxbrew/Cellar/cmake/3.16.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bmartel/open_source/st7735-raspberry-port

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bmartel/open_source/st7735-raspberry-port

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/linuxbrew/.linuxbrew/Cellar/cmake/3.16.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/linuxbrew/.linuxbrew/Cellar/cmake/3.16.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/linuxbrew/.linuxbrew/Cellar/cmake/3.16.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/linuxbrew/.linuxbrew/Cellar/cmake/3.16.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/linuxbrew/.linuxbrew/Cellar/cmake/3.16.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/linuxbrew/.linuxbrew/Cellar/cmake/3.16.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/linuxbrew/.linuxbrew/Cellar/cmake/3.16.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/linuxbrew/.linuxbrew/Cellar/cmake/3.16.2/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bmartel/open_source/st7735-raspberry-port/CMakeFiles /home/bmartel/open_source/st7735-raspberry-port/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bmartel/open_source/st7735-raspberry-port/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named st7735

# Build rule for target.
st7735: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 st7735
.PHONY : st7735

# fast build rule for target.
st7735/fast:
	$(MAKE) -f CMakeFiles/st7735.dir/build.make CMakeFiles/st7735.dir/build
.PHONY : st7735/fast

examples/main.o: examples/main.cpp.o

.PHONY : examples/main.o

# target to build an object file
examples/main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/examples/main.cpp.o
.PHONY : examples/main.cpp.o

examples/main.i: examples/main.cpp.i

.PHONY : examples/main.i

# target to preprocess a source file
examples/main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/examples/main.cpp.i
.PHONY : examples/main.cpp.i

examples/main.s: examples/main.cpp.s

.PHONY : examples/main.s

# target to generate assembly for a file
examples/main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/examples/main.cpp.s
.PHONY : examples/main.cpp.s

lib/common.o: lib/common.cpp.o

.PHONY : lib/common.o

# target to build an object file
lib/common.cpp.o:
	$(MAKE) -f CMakeFiles/st7735.dir/build.make CMakeFiles/st7735.dir/lib/common.cpp.o
.PHONY : lib/common.cpp.o

lib/common.i: lib/common.cpp.i

.PHONY : lib/common.i

# target to preprocess a source file
lib/common.cpp.i:
	$(MAKE) -f CMakeFiles/st7735.dir/build.make CMakeFiles/st7735.dir/lib/common.cpp.i
.PHONY : lib/common.cpp.i

lib/common.s: lib/common.cpp.s

.PHONY : lib/common.s

# target to generate assembly for a file
lib/common.cpp.s:
	$(MAKE) -f CMakeFiles/st7735.dir/build.make CMakeFiles/st7735.dir/lib/common.cpp.s
.PHONY : lib/common.cpp.s

lib/st7735.o: lib/st7735.cpp.o

.PHONY : lib/st7735.o

# target to build an object file
lib/st7735.cpp.o:
	$(MAKE) -f CMakeFiles/st7735.dir/build.make CMakeFiles/st7735.dir/lib/st7735.cpp.o
.PHONY : lib/st7735.cpp.o

lib/st7735.i: lib/st7735.cpp.i

.PHONY : lib/st7735.i

# target to preprocess a source file
lib/st7735.cpp.i:
	$(MAKE) -f CMakeFiles/st7735.dir/build.make CMakeFiles/st7735.dir/lib/st7735.cpp.i
.PHONY : lib/st7735.cpp.i

lib/st7735.s: lib/st7735.cpp.s

.PHONY : lib/st7735.s

# target to generate assembly for a file
lib/st7735.cpp.s:
	$(MAKE) -f CMakeFiles/st7735.dir/build.make CMakeFiles/st7735.dir/lib/st7735.cpp.s
.PHONY : lib/st7735.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... main"
	@echo "... edit_cache"
	@echo "... st7735"
	@echo "... rebuild_cache"
	@echo "... examples/main.o"
	@echo "... examples/main.i"
	@echo "... examples/main.s"
	@echo "... lib/common.o"
	@echo "... lib/common.i"
	@echo "... lib/common.s"
	@echo "... lib/st7735.o"
	@echo "... lib/st7735.i"
	@echo "... lib/st7735.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

